version: '3'
services:
  node1:
    build: .
    ports:
      - "18332:18332"
      - "18333:18333"
      - "28332:28332"
    expose: 
      - "18332"
      - "18333"
      - "28332"
    command: [ "-addnode=node2:18333", "-addnode=node3:18333", "-zmqpubhashblock=tcp://*:28332", "-zmqpubhashtx=tcp://*:28332"]
  node2:
    build: .
    ports:
      - "18501:18333"
    expose: 
      - "18333"
    command: [ "-addnode=node1:18333", "-addnode=node3:18333"]
  node3:
    build: .
    ports:
      - "18502:18333"
    expose: 
      - "18333"
    command: [ "-addnode=node2:18333", "-addnode=node1:18333"]
